### ISSUE TITLE
High Scores tracking feature

### ISSUE THREAD

**Issue by dmigwi** [dmigwi/tapoo#5]
Since the user will be playing the game online. The following should be the acceptance criteria of this epic.
- [ ] The user/player should be able to seamlessly create an Tapoo account via the terminal.
- [ ] The player should not be required to login everytime they need to play the game.
- [ ] Use that account to track the high scores.
- [ ] Add a database to store the high scores.
- [ ] Offer a URL link that allow the user to:
   - [ ] See detailed list of high scores from other people/Tapoo game players.
   - [ ] Edit/update their user profile.
